apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nim-gen-ai.fullname" . }}
  labels:
    {{- include "nim-gen-ai.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nim-gen-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nim-gen-ai.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: {{ include "nim-gen-ai.fullname" . }}-config