apiVersion: v1
kind: Service
metadata:
  name: {{ include "nim-gen-ai.fullname" . }}
  labels:
    {{- include "nim-gen-ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "nim-gen-ai.selectorLabels" . | nindent 4 }}